-- Proplet v3.34 / Generation 4 archive lineage
-- Schema-only and idempotent. Applying this migration does not switch content,
-- prune legacy puzzle bodies, reset progress, or award XP.

create table if not exists public.content_catalog (
  content_key text primary key,
  content_hash text not null unique,
  rows smallint,
  cols smallint,
  active_cells smallint,
  target_count smallint,
  archive_status text not null default 'catalogued'
    check (archive_status in ('active', 'catalogued', 'cold-archive', 'retired')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.content_catalog_contexts (
  id bigint generated by default as identity primary key,
  content_key text not null references public.content_catalog(content_key) on delete restrict,
  puzzle_id text,
  content_generation smallint,
  content_bank text not null,
  difficulty text,
  content_level integer,
  daily_date date,
  published_from timestamptz,
  published_to timestamptz,
  source_path text,
  lineage_confidence text not null default 'exact'
    check (lineage_confidence in ('exact', 'inferred', 'ambiguous')),
  created_at timestamptz not null default now()
);

create unique index if not exists content_catalog_context_exact_uq
  on public.content_catalog_contexts (
    content_key,
    coalesce(puzzle_id, ''),
    content_bank,
    coalesce(difficulty, ''),
    coalesce(content_level, -1),
    coalesce(daily_date, date '0001-01-01')
  );

create index if not exists content_catalog_context_puzzle_idx
  on public.content_catalog_contexts (puzzle_id, content_generation);
create index if not exists content_catalog_context_slot_idx
  on public.content_catalog_contexts (content_bank, difficulty, content_level, content_generation);
create index if not exists content_catalog_context_daily_idx
  on public.content_catalog_contexts (daily_date, content_generation);

alter table public.content_catalog enable row level security;
alter table public.content_catalog_contexts enable row level security;
revoke all on table public.content_catalog from anon, authenticated;
revoke all on table public.content_catalog_contexts from anon, authenticated;

alter table public.results
  add column if not exists content_key text,
  add column if not exists content_generation smallint,
  add column if not exists content_bank text,
  add column if not exists content_level integer,
  add column if not exists content_lineage_confidence text;

alter table public.puzzle_runs
  add column if not exists content_key text,
  add column if not exists content_generation smallint,
  add column if not exists content_bank text,
  add column if not exists content_level integer,
  add column if not exists content_lineage_confidence text;

alter table public.puzzle_attempts
  add column if not exists content_key text,
  add column if not exists content_generation smallint,
  add column if not exists content_bank text,
  add column if not exists content_level integer,
  add column if not exists content_lineage_confidence text;

create index if not exists results_content_lineage_idx
  on public.results (content_generation, content_bank, difficulty, content_level);
create index if not exists puzzle_runs_content_lineage_idx
  on public.puzzle_runs (content_generation, content_bank, difficulty, content_level);
create index if not exists puzzle_attempts_content_lineage_idx
  on public.puzzle_attempts (content_generation, content_bank, difficulty, content_level);

comment on table public.content_catalog is
  'Non-playable metadata catalog. Puzzle letters, paths and answers are intentionally absent.';
comment on table public.content_catalog_contexts is
  'Historical generation/bank/slot aliases for immutable content hashes.';
comment on column public.results.content_lineage_confidence is
  'exact, inferred or ambiguous; never fabricate certainty for reused legacy puzzle IDs.';

