-- Proplet v3.34 / Generation 4 archive lineage
-- Schema-only and idempotent. Applying this migration does not switch content,
-- prune legacy puzzle bodies, reset progress, or award XP.

create table if not exists public.content_catalog (
  content_key text primary key,
  content_hash text not null unique,
  rows smallint,
  cols smallint,
  active_cells smallint,
  target_count smallint,
  archive_status text not null default 'catalogued'
    check (archive_status in ('active', 'catalogued', 'cold-archive', 'retired')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.content_catalog_contexts (
  id bigint generated by default as identity primary key,
  content_key text not null references public.content_catalog(content_key) on delete restrict,
  puzzle_id text,
  content_generation smallint,
  content_bank text not null,
  difficulty text,
  content_level integer,
  daily_date date,
  published_from timestamptz,
  published_to timestamptz,
  source_path text,
  lineage_confidence text not null default 'exact'
    check (lineage_confidence in ('exact', 'inferred', 'ambiguous')),
  created_at timestamptz not null default now()
);

create unique index if not exists content_catalog_context_exact_uq
  on public.content_catalog_contexts (
    content_key,
    coalesce(puzzle_id, ''),
    content_bank,
    coalesce(difficulty, ''),
    coalesce(content_level, -1),
    coalesce(daily_date, date '0001-01-01')
  );

create index if not exists content_catalog_context_puzzle_idx
  on public.content_catalog_contexts (puzzle_id, content_generation);
create index if not exists content_catalog_context_slot_idx
  on public.content_catalog_contexts (content_bank, difficulty, content_level, content_generation);
create index if not exists content_catalog_context_daily_idx
  on public.content_catalog_contexts (daily_date, content_generation);

alter table public.content_catalog enable row level security;
alter table public.content_catalog_contexts enable row level security;
revoke all on table public.content_catalog from anon, authenticated;
revoke all on table public.content_catalog_contexts from anon, authenticated;

alter table public.results
  add column if not exists content_key text,
  add column if not exists content_generation smallint,
  add column if not exists content_bank text,
  add column if not exists content_level integer,
  add column if not exists content_lineage_confidence text;

alter table public.puzzle_runs
  add column if not exists content_key text,
  add column if not exists content_generation smallint,
  add column if not exists content_bank text,
  add column if not exists content_level integer,
  add column if not exists content_lineage_confidence text;

alter table public.puzzle_attempts
  add column if not exists content_key text,
  add column if not exists content_generation smallint,
  add column if not exists content_bank text,
  add column if not exists content_level integer,
  add column if not exists content_lineage_confidence text;

create index if not exists results_content_lineage_idx
  on public.results (content_generation, content_bank, difficulty, content_level);
create index if not exists puzzle_runs_content_lineage_idx
  on public.puzzle_runs (content_generation, content_bank, difficulty, content_level);
create index if not exists puzzle_attempts_content_lineage_idx
  on public.puzzle_attempts (content_generation, content_bank, difficulty, content_level);

comment on table public.content_catalog is
  'Non-playable metadata catalog. Puzzle letters, paths and answers are intentionally absent.';
comment on table public.content_catalog_contexts is
  'Historical generation/bank/slot aliases for immutable content hashes.';
comment on column public.results.content_lineage_confidence is
  'exact, inferred or ambiguous; never fabricate certainty for reused legacy puzzle IDs.';

create or replace function public.attach_content_lineage()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  matched_key text;
  matched_generation smallint;
  matched_bank text;
  matched_level integer;
begin
  if new.content_key is not null or new.puzzle_id is null then
    return new;
  end if;
  select
    min(content_key), min(content_generation), min(content_bank), min(content_level)
  into matched_key, matched_generation, matched_bank, matched_level
  from public.content_catalog_contexts
  where puzzle_id = new.puzzle_id
  having count(distinct content_key) = 1;
  if matched_key is not null then
    new.content_key := matched_key;
    new.content_generation := matched_generation;
    new.content_bank := coalesce(new.mode, matched_bank);
    new.content_level := matched_level;
    new.content_lineage_confidence := 'exact';
  end if;
  return new;
end;
$$;

revoke all on function public.attach_content_lineage() from public, anon, authenticated;

drop trigger if exists results_attach_content_lineage on public.results;
create trigger results_attach_content_lineage
before insert or update of puzzle_id on public.results
for each row execute function public.attach_content_lineage();

drop trigger if exists puzzle_runs_attach_content_lineage on public.puzzle_runs;
create trigger puzzle_runs_attach_content_lineage
before insert or update of puzzle_id on public.puzzle_runs
for each row execute function public.attach_content_lineage();

drop trigger if exists puzzle_attempts_attach_content_lineage on public.puzzle_attempts;
create trigger puzzle_attempts_attach_content_lineage
before insert or update of puzzle_id on public.puzzle_attempts
for each row execute function public.attach_content_lineage();

create or replace view public.content_archive_stats
with (security_invoker = true)
as
select
  c.content_generation,
  c.content_bank,
  c.difficulty,
  count(distinct c.content_key) as puzzle_count,
  count(distinct r.id) as completed_results,
  count(distinct pr.id) as completed_runs
from public.content_catalog_contexts c
left join public.results r on r.content_key = c.content_key
left join public.puzzle_runs pr on pr.content_key = c.content_key
group by c.content_generation, c.content_bank, c.difficulty;

revoke all on table public.content_archive_stats from anon, authenticated;
