const assert=require("assert");
const fs=require("fs");
const path=require("path");
const root=path.resolve(__dirname,"..");
const app=fs.readFileSync(path.join(root,"public/app.js"),"utf8");
const html=fs.readFileSync(path.join(root,"public/index.html"),"utf8");
const css=fs.readFileSync(path.join(root,"public/styles.css"),"utf8");
assert(!html.includes("landscapeGameBlocker"),"orientation blocker DOM must be removed");
assert(!html.includes("Otoč telefon na výšku"),"rotation prompt must be removed");
assert(!app.includes("shouldBlockPhoneLandscape"),"viewport classifier must not block play");
assert(!app.includes("pauseGameClock('landscape')"),"orientation must never pause the clock");
assert(!css.includes("body.landscape-game-blocked .landscape-game-blocker"),"blocking CSS must be removed");
assert(app.includes("ResizeObserver"),"board must still reflow when its stage changes");
assert(app.includes("window.addEventListener('orientationchange',settleViewportChange)"),"orientation change must trigger responsive reflow");
assert(app.includes("window.visualViewport?.addEventListener?.('resize',settleViewportChange)"),"visualViewport resize must trigger responsive reflow");
console.log("PASS: v3.21.3 orientation never blocks play; responsive reflow retained");
