#!/usr/bin/env python3
from pathlib import Path
import json
import subprocess

ROOT = Path(__file__).resolve().parents[2]
PUBLIC = ROOT / "public"
read = lambda path: (ROOT / path).read_text(encoding="utf-8")

index = read("public/index.html")
theme = read("public/theme-init.js")
runtime = read("public/runtime-meta.js")
sw = read("public/sw.js")
vercel = read("vercel.json")
manifest = json.loads(read("tests/current/manifest.json"))

# These audit-era files look old but are still live runtime dependencies today.
for asset in (
    "/p0-hotfix-v3336.css",
    "/p0-hotfix-v3336.js",
    "/push-origin-v3325.js?v=2",
    "/quality-hotfix-v334.css",
):
    assert asset in runtime, asset

# These candidates are not part of the current production load chain.
dead_candidates = (
    "game-layout-v3323.js",
    "release-notes.js",
    "release-notes.css",
    "valid-word-feedback-v3328.js",
    "server.py",
)
load_chain = "\n".join((index, theme, runtime, sw, vercel))
for name in dead_candidates:
    if name == "server.py":
        # Root server.py is the runtime backend; only a public/server.py reference would be invalid.
        assert "/server.py" not in load_chain
    else:
        assert name not in load_chain, name

# Historical v3 release tests are explicit evidence and not part of the default current gate.
legacy = manifest["legacy_evidence"]
assert "Historical release/regression evidence" in legacy["description"]
assert "tools/test_v3*.py" in legacy["globs"]
assert "tools/test_v3*.js" in legacy["globs"]
current_paths = {item["path"] for item in manifest["current"]["tests"]}
# Explicitly promoted historical-version tests may remain current; the legacy glob
# is a default lifecycle classification, not a ban on reviewed current exceptions.
assert "tools/test_v319_focus_pause.js" in current_paths

# The repository cleanup contract is about versioned source, not ignored local
# interpreter debris. Stale __pycache__ files in a developer workspace must not
# make the runtime gate red as long as no generated bytecode is tracked.
legacy_server = PUBLIC / "server.py"
if not legacy_server.exists():
    tracked = subprocess.run(
        ["git", "ls-files"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.splitlines()
    tracked_bytecode = [
        path for path in tracked
        if "/__pycache__/" in f"/{path}"
        or Path(path).suffix.lower() in {".pyc", ".pyo", ".pyd"}
    ]
    assert not tracked_bytecode, tracked_bytecode
    gitignore = read(".gitignore")
    assert "__pycache__/" in gitignore
    assert "*.py[cod]" in gitignore

print("PASS Sprint 16 legacy reachability characterization")
