#!/usr/bin/env python3
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[2]
PUBLIC = ROOT / "public"
read = lambda path: (ROOT / path).read_text(encoding="utf-8")

index = read("public/index.html")
theme = read("public/theme-init.js")
runtime = read("public/runtime-meta.js")
sw = read("public/sw.js")
vercel = read("vercel.json")
manifest = json.loads(read("tests/current/manifest.json"))

# These audit-era files look old but are still live runtime dependencies today.
for asset in (
    "/p0-hotfix-v3336.css",
    "/p0-hotfix-v3336.js",
    "/push-origin-v3325.js?v=2",
    "/quality-hotfix-v334.css",
):
    assert asset in runtime, asset

# These candidates are not part of the current production load chain.
dead_candidates = (
    "game-layout-v3323.js",
    "release-notes.js",
    "release-notes.css",
    "valid-word-feedback-v3328.js",
    "server.py",
)
load_chain = "\n".join((index, theme, runtime, sw, vercel))
for name in dead_candidates:
    if name == "server.py":
        # Root server.py is the runtime backend; only a public/server.py reference would be invalid.
        assert "/server.py" not in load_chain
    else:
        assert name not in load_chain, name

# Historical v3 release tests are explicit evidence and not part of the default current gate.
legacy = manifest["legacy_evidence"]
assert "Historical release/regression evidence" in legacy["description"]
assert "tools/test_v3*.py" in legacy["globs"]
assert "tools/test_v3*.js" in legacy["globs"]
current_paths = {item["path"] for item in manifest["current"]["tests"]}
assert not any(path.startswith("tools/test_v3") for path in current_paths)

# Baseline may still contain generated bytecode and the historical static backend;
# the cleanup state must remove them rather than treating them as runtime dependencies.
legacy_server = PUBLIC / "server.py"
pycache = ROOT / "tools" / "__pycache__"
if not legacy_server.exists():
    assert not list(pycache.glob("*.pyc")) if pycache.exists() else True

print("PASS Sprint 16 legacy reachability characterization")
